name: Check Translations

on:
  push:
  pull_request:

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install argostranslate
      - name: Verify translations
        run: |
          set -e
          python Tools/fix_tokens.py --check-only --reorder Resources/Localization/Messages/*.json
          dotnet run --project Bloodcraft.csproj -p:RunGenerateREADME=false -- check-translations
